In [1]:
import pandas as pd
import numpy as np
import seaborn as sns 
import os

In [2]:
path=r'E:\notes\Prodigy Infotech\Task04\archive'
os.chdir(path)

In [3]:
dt=pd.read_csv("twitter_training.csv",delimiter=',')
dv = pd.read_csv("twitter_validation.csv",delimiter=',')

In [4]:
dt.head()

ID        Topic Sentiment  \
0  2401  Borderlands  Positive   
1  2401  Borderlands  Positive   
2  2401  Borderlands  Positive   
3  2401  Borderlands  Positive   
4  2401  Borderlands  Positive   

                                             Comment  
0  im getting on borderlands and i will murder yo...  
1  I am coming to the borders and I will kill you...  
2  im getting on borderlands and i will kill you ...  
3  im coming on borderlands and i will murder you...  
4  im getting on borderlands 2 and i will murder ...

In [5]:
dv.head()

ID      Topic   Sentiment  \
0  3364   Facebook  Irrelevant   
1   352     Amazon     Neutral   
2  8312  Microsoft    Negative   
3  4371      CS-GO    Negative   
4  4433     Google     Neutral   

                                             Comment  
0  I mentioned on Facebook that I was struggling ...  
1  BBC News - Amazon boss Jeff Bezos rejects clai...  
2  @Microsoft Why do I pay for WORD when it funct...  
3  CSGO matchmaking is so full of closet hacking,...  
4  Now the President is slapping Americans in the...

In [6]:
dv.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 4 columns):
 #   Column     Non-Null Count  Dtype 
---  ------     --------------  ----- 
 0   ID         1000 non-null   int64 
 1   Topic      1000 non-null   object
 2   Sentiment  1000 non-null   object
 3   Comment    1000 non-null   object
dtypes: int64(1), object(3)
memory usage: 31.4+ KB


In [7]:
dt.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 74682 entries, 0 to 74681
Data columns (total 4 columns):
 #   Column     Non-Null Count  Dtype 
---  ------     --------------  ----- 
 0   ID         74682 non-null  int64 
 1   Topic      74682 non-null  object
 2   Sentiment  74682 non-null  object
 3   Comment    73996 non-null  object
dtypes: int64(1), object(3)
memory usage: 2.3+ MB


In [8]:
dv.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 4 columns):
 #   Column     Non-Null Count  Dtype 
---  ------     --------------  ----- 
 0   ID         1000 non-null   int64 
 1   Topic      1000 non-null   object
 2   Sentiment  1000 non-null   object
 3   Comment    1000 non-null   object
dtypes: int64(1), object(3)
memory usage: 31.4+ KB


In [9]:
dt.isna().sum()

ID             0
Topic          0
Sentiment      0
Comment      686
dtype: int64

In [10]:
dv.isna().sum()

ID           0
Topic        0
Sentiment    0
Comment      0
dtype: int64

In [11]:
dt.duplicated().sum()

2701

In [12]:
dv.duplicated().sum()

0

In [13]:
dv.shape

(1000, 4)

In [14]:
dt.shape

(74682, 4)

In [15]:
dv.shape

(1000, 4)

In [16]:
dt.columns

Index(['ID', 'Topic', 'Sentiment', 'Comment'], dtype='object')

In [17]:
dv.columns

Index(['ID', 'Topic', 'Sentiment', 'Comment'], dtype='object')

In [18]:
dt.describe()

ID
count  74682.000000
mean    6432.586165
std     3740.427870
min        1.000000
25%     3195.000000
50%     6422.000000
75%     9601.000000
max    13200.000000

In [19]:
dv.describe()

ID
count   1000.000000
mean    6432.088000
std     3728.310569
min        6.000000
25%     3247.750000
50%     6550.000000
75%     9661.750000
max    13197.000000

In [20]:
dv.dtypes

ID            int64
Topic        object
Sentiment    object
Comment      object
dtype: object

In [21]:
dt.dtypes

ID            int64
Topic        object
Sentiment    object
Comment      object
dtype: object

In [22]:
dt['Comment'] = dt['Comment'].astype(str) 

In [23]:
dv['Comment'] = dv['Comment'].astype(str) 

In [24]:
import re
from nltk.corpus import stopwords
import nltk

nltk.download('stopwords')
stop_words = set(stopwords.words('english'))

# Function to clean text data
def clean_text(Comment):
    Comment = re.sub(r'http\S+', '', Comment) # Remove URLs
    Comment = re.sub(r'@\w+', '', Comment)    # Remove mentions
    Comment = re.sub(r'#', '', Comment)       # Remove hashtag symbols
    Comment = re.sub(r'[^A-Za-z\s]', '', Comment) # Remove non-alphabetic characters
    Comment = Comment.lower()                 # Convert to lowercase
    Comment = ' '.join([word for word in Comment.split() if word not in stop_words]) # Remove stopwords
    return Comment

# Apply the function to clean both training and validation datasets
dt['Cleaned_Comment'] = dt['Comment'].apply(clean_text)
dv['Cleaned_Comment'] = dv['Comment'].apply(clean_text)

# Check cleaned text
print(dt['Cleaned_Comment'].head())
print(dv['Cleaned_Comment'].head())


[nltk_data] Downloading package stopwords to C:\Users\Souymo
[nltk_data]     Tewari\AppData\Roaming\nltk_data...
[nltk_data]   Package stopwords is already up-to-date!


0    im getting borderlands murder
1              coming borders kill
2      im getting borderlands kill
3     im coming borderlands murder
4    im getting borderlands murder
Name: Cleaned_Comment, dtype: object
0    mentioned facebook struggling motivation go ru...
1    bbc news amazon boss jeff bezos rejects claims...
2                 pay word functions poorly chromebook
3    csgo matchmaking full closet hacking truly awf...
4    president slapping americans face really commi...
Name: Cleaned_Comment, dtype: object


In [25]:
from sklearn.feature_extraction.text import TfidfVectorizer
# Create TF-IDF vectors
tfidf = TfidfVectorizer(max_features=5000)
X_train = tfidf.fit_transform(dt['Cleaned_Comment']).toarray()
X_valid = tfidf.transform(dv['Cleaned_Comment']).toarray()
y_train = dt['Sentiment']  # Assuming the sentiment column is the target
y_valid = dv['Sentiment']  # Assuming the sentiment column is the target
print(X_train.shape, X_valid.shape)

(74682, 5000) (1000, 5000)


# Training a classifier model like logistic regression on training data

In [53]:
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import classification_report, confusion_matrix, accuracy_score
# Train Logistic Regression model
model = LogisticRegression(max_iter=1000)
model.fit(X_train, y_train)
# Predict on validation data
y_pred = model.predict(X_valid)
# Evaluate the model
print("Validation Accuracy:", accuracy_score(y_valid, y_pred))
print("Confusion Matrix:\n", confusion_matrix(y_valid, y_pred))
print("Classification Report:\n", classification_report(y_valid, y_pred))

Validation Accuracy: 0.8
Confusion Matrix:
 [[113  27  12  20]
 [  5 233  16  12]
 [ 13  35 215  22]
 [ 10  18  10 239]]
Classification Report:
               precision    recall  f1-score   support

  Irrelevant       0.80      0.66      0.72       172
    Negative       0.74      0.88      0.80       266
     Neutral       0.85      0.75      0.80       285
    Positive       0.82      0.86      0.84       277

    accuracy                           0.80      1000
   macro avg       0.80      0.79      0.79      1000
weighted avg       0.80      0.80      0.80      1000



# Tuning hyper parameters with GridSearchCV to get best possible models

In [ ]:
from sklearn.model_selection import GridSearchCV

# Define hyperparameters for tuning
param_grid = {
    'C': [0.01, 0.1, 1, 10],
    'penalty': ['l2'],
}
# Perform Grid Search
grid_search = GridSearchCV(LogisticRegression(max_iter=1000), param_grid, cv=5)
grid_search.fit(X_train, y_train)
# Use the best model
best_model = grid_search.best_estimator_
# Predict and evaluate
y_pred_best = best_model.predict(X_valid)
print("Best Validation Accuracy:", accuracy_score(y_valid, y_pred_best))
print("Confusion Matrix:\n", confusion_matrix(y_valid, y_pred_best))
print("Classification Report:\n", classification_report(y_valid, y_pred_best))
